server:
  port: 11111

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:5173
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      server:
        webmvc:
          routes:
            - id: authentication-service-route
              uri: http://auth-service:11112
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=2

            - id: auth-service-swagger
              uri: http://auth-service:11112
              predicates:
                - Path=/v3/api-docs/**

