spring:
  application:
    name: user-service

server:
  port: 11113

springdoc:
  swagger-ui:
    config-url: /api/user/v3/api-docs/swagger-config
    url: /api/user/v3/api-docs
    path: /api/user/v3/swagger-ui
