spring:
  application:
    name: user-service

  neo4j:
    uri: #URL
    authentication:
      username: #username
      password: #password

  datasource:
    url: #url
    username: #username
    password: #password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 11113

springdoc:
  swagger-ui:
    config-url: /api/user/v3/api-docs/swagger-config
    url: /api/user/v3/api-docs
    path: /v3/swagger-ui
